#
#  Author: PB
#  Maintainer: PB
#  License: (c) HRDAG 2018, some rights reserved: GPL v2 or newer
#
# pdp-poc/task1a/Makefile
#
# this example has *no* dependencies, it simulates data.
#
output/task1a.csv:
	Rscript --no-site-init src/gennums.R

# done.
